### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by john-h-k** [Angourisoft/MathS#1]
Hi,

Just noticed you seem to have the exact same name as my repo, https://github.com/john-h-k/MathSharp. This could potentially be an issue for both of us?

**Comment by Angourisoft** [comment]
Hello, John.
I see. Seems like I have to change it. By the way, am I right that
functional of the two libraries is completely different? Mine is for some
algebraic expressions (e. g. find derivative of a function).

пт, 6 дек. 2019 г. в 23:43, John <notifications@github.com>:

**Comment by john-h-k** [comment]
Yeah, functionally they are different. Mine is a vector/matrix hardware accelerated style one (but yours is completely awesome! :)).
If you would change the name, I would massively appreciate it, as MathSharp already has reasonable traction, and it causes particular conflicts on Nuget, where you currently have the `MathSharp` package name

**Comment by Angourisoft** [comment]
Ok, I will change it in a very short time. Just curious: what conflict are you talking about? I cannot find MathSharp package on Nuget (besides mine)

**Comment by john-h-k** [comment]
I am sure your project will rapidly pick up speed as it is very cool - just not ideal to have people going "I am trying to download MathSharp and am downloading this unrelated project instead" and asking me about it :))

**Comment by Angourisoft** [comment]
Sorry :). The project's been renamed

**Comment by john-h-k** [comment]
Could you delete the project so it is possible to make the `MathSharp` nuget public? As yours is still listed, just deprecated. Thanks in advance

**Comment by Angourisoft** [comment]
As I just found out, the package cannot deleted permanently from nuget. I unlisted it. If you still can't publish your package, contact me via Discord (Oryp4ik#0120) ("chatting" on github is not very efficient) or suggest your way to communicate.

**Comment by john-h-k** [comment]
You can transfer ownership of the `MathSharp` package to me, and I can work from there :)

**Comment by Perksey** [comment]
You'll have to contact support to have them permenantly delete the package no matter what, as John will be unable to push the actual MathSharp 1.0 as that version number has already been taken.

**Comment by Perksey** [comment]
Please see this article for more info: https://docs.microsoft.com/en-gb/nuget/nuget-org/policies/deleting-packages

**Comment by Angourisoft** [comment]
I have already sent an email to Nuget.

**Comment by Perksey** [comment]
Thanks, let me know how it goes :)

**Comment by Angourisoft** [comment]
Removed.

**Comment by Perksey** [comment]
Unfortunately, it has not been permenantly removed and has only been delisted as we are still unable to claim the package name. We're going to have to wait until NuGet Support gets back to us.

**Comment by Angourisoft** [comment]
@john-h-k, Im ready to transfer ownership to you. Do I transfer it to johnkellyoxford@gmail.com?

**Comment by Perksey** [comment]
@Angourisoft The package is still up there, while delisted. You need to contact NuGet Support to get it permenantly removed otherwise John won't be able to post any packages with any of the version numbers you've already taken.

**Comment by Angourisoft** [comment]
> Completely deleting the package would create a situation where anyone would be able to claim the ownership of the package ID. If you want a certain person to get the ownership, please, add them specifically as the package owner using the “Manage package” page linked on the package details page. We can then work with the new owner if they find it necessary to delete already published (and now unlisted and deprecated) versions of the package.
(c) Nuget support

**Comment by Perksey** [comment]
Ah alright. @john-h-k did you want me to take care of the NuGet stuff?
